[package]
name = "nu_plugin_plist"
description = "Plist parsing for nushell"
version = "0.1.6"
edition = "2021"
license = "MIT"


[dependencies]
nu-protocol = { version = "0.87.1", features = ["plugin"] }
plist = "^1.6"
nu-plugin = "0.87.1"
chrono = "^0.4"
