[package]
name = "nu_plugin_plist"
description = "Plist parsing for nushell"
version = "0.1.6"
edition = "2021"
license = "MIT"


[dependencies]
plist = "1.6"
nu-plugin = "^0.88"
nu-protocol = "^0.88"
chrono = "^0.4"
